[package]
name = "amethyst-extra"
version = "0.4.0"
authors = ["jojolepro <jojolepromain@gmail.com>"]
description = "Various helpful components, structs, systems and resources for the Amethyst engine."
categories = ["game-engines"]
keywords = ["amethyst", "extra", "utils", "controllers", "fps", "physics"]
documentation = "https://docs.rs/amethyst-extra"
repository = "https://github.com/jojolepro/amethyst-extra"
license = "Apache-2.0"
exclude = ["doc"]

[dependencies]
amethyst = "0.9"
discord-rpc-client = "0.2.3"
partial_function = "0.4.0"
serde = { version = "1.0", features = ["serde_derive"] }
serde_derive = "1.0"
ron = "0.2"
log = "0.4"
dirty = "0.2"
fern = { version = "0.5", features = ["colored"] }
crossterm = "0.4.2"
rand = "0.5.5"
lazy_static = "1.1.0"
derive-new = "0.5"
#specs-derive = { git = "https://github.com/slide-rs/specs" }
amethyst-rhusics = "0.3"

#amethyst = { git = "https://github.com/amethyst/amethyst", features = ["nightly"] }
#amethyst-rhusics = { git = "https://github.com/amethyst/amethyst-rhusics" }
